/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt --set-package=janus-pp-rec --set-version=0.11.3 -F postprocessing/pp-cmdline 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "postprocessing/pp-cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: janus-pp-rec [OPTIONS] source.mjr\n[destination.[opus|ogg|mka|wav|webm|mkv|h264|srt]]";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -F, --file-extensions         Only print the supported target file extensions\n                                  per codec  (default=off)",
  "  -j, --json                    Only print JSON header  (default=off)",
  "  -H, --header                  Only parse .mjr header  (default=off)",
  "  -p, --parse                   Only parse and re-order packets  (default=off)",
  "  -m, --metadata=metadata       Save this metadata string in the target file",
  "  -i, --ignore-first=count      Number of first packets to ignore when\n                                  processing, e.g., in case they're cause of\n                                  issues (default=0)",
  "  -P, --payload-type=pt         Ignore all RTP packets that don't match the\n                                  specified payload type (default=none)",
  "  -a, --audiolevel-ext=id       ID of the audio-levels RTP extension\n                                  (default=none)",
  "  -v, --videoorient-ext=id      ID of the video-orientation RTP extension\n                                  (default=none)",
  "  -d, --debug-level=1-7         Debug/logging level (0=disable debugging,\n                                  7=maximum debug level; default=4)",
  "  -D, --debug-timestamps        Enable debug/logging timestamps  (default=off)",
  "  -o, --disable-colors          Disable color in the logging  (default=off)",
  "  -f, --format=STRING           Specifies the output format (overrides the\n                                  format from the destination)  (possible\n                                  values=\"opus\", \"ogg\", \"mka\", \"wav\",\n                                  \"webm\", \"mkv\", \"mp4\", \"srt\")",
  "  -t, --faststart               For mp4 files write the MOOV atom at the head\n                                  of the file  (default=off)",
  "  -S, --audioskew=milliseconds  Time threshold to trigger an audio skew\n                                  compensation, disabled if 0 (default=0)",
  "  -C, --silence-distance=count  RTP packets distance used to detect RTP silence\n                                  suppression, disabled if 0 (default=100)",
  "  -r, --restamp=count           If the latency of a packet is bigger than the\n                                  `moving_average_latency * (<restamp>/1000)`\n                                  the timestamps will be corrected, disabled if\n                                  0 (default=0)",
  "  -c, --restamp-packets=count   Number of packets used for calculating moving\n                                  average latency for timestamp correction\n                                  (default=10)",
  "  -n, --restamp-min-th=milliseconds\n                                Minimum latency of moving average to reach\n                                  before starting to correct timestamps.\n                                  (default=500)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


const char *cmdline_parser_format_values[] = {"opus", "ogg", "mka", "wav", "webm", "mkv", "mp4", "srt", 0}; /*< Possible values for format. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->file_extensions_given = 0 ;
  args_info->json_given = 0 ;
  args_info->header_given = 0 ;
  args_info->parse_given = 0 ;
  args_info->metadata_given = 0 ;
  args_info->ignore_first_given = 0 ;
  args_info->payload_type_given = 0 ;
  args_info->audiolevel_ext_given = 0 ;
  args_info->videoorient_ext_given = 0 ;
  args_info->debug_level_given = 0 ;
  args_info->debug_timestamps_given = 0 ;
  args_info->disable_colors_given = 0 ;
  args_info->format_given = 0 ;
  args_info->faststart_given = 0 ;
  args_info->audioskew_given = 0 ;
  args_info->silence_distance_given = 0 ;
  args_info->restamp_given = 0 ;
  args_info->restamp_packets_given = 0 ;
  args_info->restamp_min_th_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->file_extensions_flag = 0;
  args_info->json_flag = 0;
  args_info->header_flag = 0;
  args_info->parse_flag = 0;
  args_info->metadata_arg = NULL;
  args_info->metadata_orig = NULL;
  args_info->ignore_first_orig = NULL;
  args_info->payload_type_orig = NULL;
  args_info->audiolevel_ext_orig = NULL;
  args_info->videoorient_ext_orig = NULL;
  args_info->debug_level_orig = NULL;
  args_info->debug_timestamps_flag = 0;
  args_info->disable_colors_flag = 0;
  args_info->format_arg = NULL;
  args_info->format_orig = NULL;
  args_info->faststart_flag = 0;
  args_info->audioskew_orig = NULL;
  args_info->silence_distance_orig = NULL;
  args_info->restamp_orig = NULL;
  args_info->restamp_packets_orig = NULL;
  args_info->restamp_min_th_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->file_extensions_help = gengetopt_args_info_help[2] ;
  args_info->json_help = gengetopt_args_info_help[3] ;
  args_info->header_help = gengetopt_args_info_help[4] ;
  args_info->parse_help = gengetopt_args_info_help[5] ;
  args_info->metadata_help = gengetopt_args_info_help[6] ;
  args_info->ignore_first_help = gengetopt_args_info_help[7] ;
  args_info->payload_type_help = gengetopt_args_info_help[8] ;
  args_info->audiolevel_ext_help = gengetopt_args_info_help[9] ;
  args_info->videoorient_ext_help = gengetopt_args_info_help[10] ;
  args_info->debug_level_help = gengetopt_args_info_help[11] ;
  args_info->debug_timestamps_help = gengetopt_args_info_help[12] ;
  args_info->disable_colors_help = gengetopt_args_info_help[13] ;
  args_info->format_help = gengetopt_args_info_help[14] ;
  args_info->faststart_help = gengetopt_args_info_help[15] ;
  args_info->audioskew_help = gengetopt_args_info_help[16] ;
  args_info->silence_distance_help = gengetopt_args_info_help[17] ;
  args_info->restamp_help = gengetopt_args_info_help[18] ;
  args_info->restamp_packets_help = gengetopt_args_info_help[19] ;
  args_info->restamp_min_th_help = gengetopt_args_info_help[20] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->metadata_arg));
  free_string_field (&(args_info->metadata_orig));
  free_string_field (&(args_info->ignore_first_orig));
  free_string_field (&(args_info->payload_type_orig));
  free_string_field (&(args_info->audiolevel_ext_orig));
  free_string_field (&(args_info->videoorient_ext_orig));
  free_string_field (&(args_info->debug_level_orig));
  free_string_field (&(args_info->format_arg));
  free_string_field (&(args_info->format_orig));
  free_string_field (&(args_info->audioskew_orig));
  free_string_field (&(args_info->silence_distance_orig));
  free_string_field (&(args_info->restamp_orig));
  free_string_field (&(args_info->restamp_packets_orig));
  free_string_field (&(args_info->restamp_min_th_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->file_extensions_given)
    write_into_file(outfile, "file-extensions", 0, 0 );
  if (args_info->json_given)
    write_into_file(outfile, "json", 0, 0 );
  if (args_info->header_given)
    write_into_file(outfile, "header", 0, 0 );
  if (args_info->parse_given)
    write_into_file(outfile, "parse", 0, 0 );
  if (args_info->metadata_given)
    write_into_file(outfile, "metadata", args_info->metadata_orig, 0);
  if (args_info->ignore_first_given)
    write_into_file(outfile, "ignore-first", args_info->ignore_first_orig, 0);
  if (args_info->payload_type_given)
    write_into_file(outfile, "payload-type", args_info->payload_type_orig, 0);
  if (args_info->audiolevel_ext_given)
    write_into_file(outfile, "audiolevel-ext", args_info->audiolevel_ext_orig, 0);
  if (args_info->videoorient_ext_given)
    write_into_file(outfile, "videoorient-ext", args_info->videoorient_ext_orig, 0);
  if (args_info->debug_level_given)
    write_into_file(outfile, "debug-level", args_info->debug_level_orig, 0);
  if (args_info->debug_timestamps_given)
    write_into_file(outfile, "debug-timestamps", 0, 0 );
  if (args_info->disable_colors_given)
    write_into_file(outfile, "disable-colors", 0, 0 );
  if (args_info->format_given)
    write_into_file(outfile, "format", args_info->format_orig, cmdline_parser_format_values);
  if (args_info->faststart_given)
    write_into_file(outfile, "faststart", 0, 0 );
  if (args_info->audioskew_given)
    write_into_file(outfile, "audioskew", args_info->audioskew_orig, 0);
  if (args_info->silence_distance_given)
    write_into_file(outfile, "silence-distance", args_info->silence_distance_orig, 0);
  if (args_info->restamp_given)
    write_into_file(outfile, "restamp", args_info->restamp_orig, 0);
  if (args_info->restamp_packets_given)
    write_into_file(outfile, "restamp-packets", args_info->restamp_packets_orig, 0);
  if (args_info->restamp_min_th_given)
    write_into_file(outfile, "restamp-min-th", args_info->restamp_min_th_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "file-extensions",	0, NULL, 'F' },
        { "json",	0, NULL, 'j' },
        { "header",	0, NULL, 'H' },
        { "parse",	0, NULL, 'p' },
        { "metadata",	1, NULL, 'm' },
        { "ignore-first",	1, NULL, 'i' },
        { "payload-type",	1, NULL, 'P' },
        { "audiolevel-ext",	1, NULL, 'a' },
        { "videoorient-ext",	1, NULL, 'v' },
        { "debug-level",	1, NULL, 'd' },
        { "debug-timestamps",	0, NULL, 'D' },
        { "disable-colors",	0, NULL, 'o' },
        { "format",	1, NULL, 'f' },
        { "faststart",	0, NULL, 't' },
        { "audioskew",	1, NULL, 'S' },
        { "silence-distance",	1, NULL, 'C' },
        { "restamp",	1, NULL, 'r' },
        { "restamp-packets",	1, NULL, 'c' },
        { "restamp-min-th",	1, NULL, 'n' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVFjHpm:i:P:a:v:d:Dof:tS:C:r:c:n:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'F':	/* Only print the supported target file extensions per codec.  */
        
        
          if (update_arg((void *)&(args_info->file_extensions_flag), 0, &(args_info->file_extensions_given),
              &(local_args_info.file_extensions_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "file-extensions", 'F',
              additional_error))
            goto failure;
        
          break;
        case 'j':	/* Only print JSON header.  */
        
        
          if (update_arg((void *)&(args_info->json_flag), 0, &(args_info->json_given),
              &(local_args_info.json_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "json", 'j',
              additional_error))
            goto failure;
        
          break;
        case 'H':	/* Only parse .mjr header.  */
        
        
          if (update_arg((void *)&(args_info->header_flag), 0, &(args_info->header_given),
              &(local_args_info.header_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "header", 'H',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Only parse and re-order packets.  */
        
        
          if (update_arg((void *)&(args_info->parse_flag), 0, &(args_info->parse_given),
              &(local_args_info.parse_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "parse", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Save this metadata string in the target file.  */
        
        
          if (update_arg( (void *)&(args_info->metadata_arg), 
               &(args_info->metadata_orig), &(args_info->metadata_given),
              &(local_args_info.metadata_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "metadata", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* Number of first packets to ignore when processing, e.g., in case they're cause of issues (default=0).  */
        
        
          if (update_arg( (void *)&(args_info->ignore_first_arg), 
               &(args_info->ignore_first_orig), &(args_info->ignore_first_given),
              &(local_args_info.ignore_first_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "ignore-first", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'P':	/* Ignore all RTP packets that don't match the specified payload type (default=none).  */
        
        
          if (update_arg( (void *)&(args_info->payload_type_arg), 
               &(args_info->payload_type_orig), &(args_info->payload_type_given),
              &(local_args_info.payload_type_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "payload-type", 'P',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* ID of the audio-levels RTP extension (default=none).  */
        
        
          if (update_arg( (void *)&(args_info->audiolevel_ext_arg), 
               &(args_info->audiolevel_ext_orig), &(args_info->audiolevel_ext_given),
              &(local_args_info.audiolevel_ext_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "audiolevel-ext", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* ID of the video-orientation RTP extension (default=none).  */
        
        
          if (update_arg( (void *)&(args_info->videoorient_ext_arg), 
               &(args_info->videoorient_ext_orig), &(args_info->videoorient_ext_given),
              &(local_args_info.videoorient_ext_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "videoorient-ext", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Debug/logging level (0=disable debugging, 7=maximum debug level; default=4).  */
        
        
          if (update_arg( (void *)&(args_info->debug_level_arg), 
               &(args_info->debug_level_orig), &(args_info->debug_level_given),
              &(local_args_info.debug_level_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "debug-level", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'D':	/* Enable debug/logging timestamps.  */
        
        
          if (update_arg((void *)&(args_info->debug_timestamps_flag), 0, &(args_info->debug_timestamps_given),
              &(local_args_info.debug_timestamps_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "debug-timestamps", 'D',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Disable color in the logging.  */
        
        
          if (update_arg((void *)&(args_info->disable_colors_flag), 0, &(args_info->disable_colors_given),
              &(local_args_info.disable_colors_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "disable-colors", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Specifies the output format (overrides the format from the destination).  */
        
        
          if (update_arg( (void *)&(args_info->format_arg), 
               &(args_info->format_orig), &(args_info->format_given),
              &(local_args_info.format_given), optarg, cmdline_parser_format_values, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "format", 'f',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* For mp4 files write the MOOV atom at the head of the file.  */
        
        
          if (update_arg((void *)&(args_info->faststart_flag), 0, &(args_info->faststart_given),
              &(local_args_info.faststart_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "faststart", 't',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* Time threshold to trigger an audio skew compensation, disabled if 0 (default=0).  */
        
        
          if (update_arg( (void *)&(args_info->audioskew_arg), 
               &(args_info->audioskew_orig), &(args_info->audioskew_given),
              &(local_args_info.audioskew_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "audioskew", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'C':	/* RTP packets distance used to detect RTP silence suppression, disabled if 0 (default=100).  */
        
        
          if (update_arg( (void *)&(args_info->silence_distance_arg), 
               &(args_info->silence_distance_orig), &(args_info->silence_distance_given),
              &(local_args_info.silence_distance_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "silence-distance", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* If the latency of a packet is bigger than the `moving_average_latency * (<restamp>/1000)` the timestamps will be corrected, disabled if 0 (default=0).  */
        
        
          if (update_arg( (void *)&(args_info->restamp_arg), 
               &(args_info->restamp_orig), &(args_info->restamp_given),
              &(local_args_info.restamp_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "restamp", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Number of packets used for calculating moving average latency for timestamp correction (default=10).  */
        
        
          if (update_arg( (void *)&(args_info->restamp_packets_arg), 
               &(args_info->restamp_packets_orig), &(args_info->restamp_packets_given),
              &(local_args_info.restamp_packets_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "restamp-packets", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Minimum latency of moving average to reach before starting to correct timestamps. (default=500).  */
        
        
          if (update_arg( (void *)&(args_info->restamp_min_th_arg), 
               &(args_info->restamp_min_th_orig), &(args_info->restamp_min_th_given),
              &(local_args_info.restamp_min_th_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "restamp-min-th", 'n',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



	FIX_UNUSED(check_required);

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
